name = "thetimevortex-pages-dev"
compatibility_date = "2025-09-05"
pages_build_output_dir = "."

[vars]  # non-secret defaults (ok to commit if you want)
BASE_URL = "https://beta.thetimevortex-website.pages.dev/"
