name = "thetimevortex-pages-dev"
compatibility_date = "2025-09-05"
pages_build_output_dir = "."

# non-secret, only used for local dev
[vars]
BASE_URL = "http://127.0.0.1:8788"

# D1 binding for local dev + CLI
[[d1_databases]]
binding = "DB"                  # <- this is what your code uses: env.DB
database_name = "ttv-admin"     # <- you’ll create this below
database_id = "8febdaa1-8b35-4ebc-97a7-6b279d922f5b"      # <- paste the ID after creation
