CREATE TABLE IF NOT EXISTS users (
  id TEXT PRIMARY KEY,
  username TEXT NOT NULL,
  created_at TEXT NOT NULL DEFAULT (CURRENT_TIMESTAMP)
);

CREATE TABLE IF NOT EXISTS admin (
  user_id TEXT PRIMARY KEY REFERENCES users(id) ON DELETE CASCADE,
  added_by TEXT NOT NULL,
  created_at TEXT NOT NULL DEFAULT (CURRENT_TIMESTAMP)
);

CREATE TABLE IF NOT EXISTS admin_audit (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  actor_user_id TEXT NOT NULL,
  target_user_id TEXT NOT NULL,
  action TEXT NOT NULL,
  created_at TEXT NOT NULL DEFAULT (CURRENT_TIMESTAMP)
);

-- seed initial admin
INSERT OR IGNORE INTO users (id, username) VALUES ('624961413500108830', 'TheDoctorTTV');
INSERT OR IGNORE INTO admin (user_id, added_by) VALUES ('624961413500108830', '624961413500108830');
